server:
  port: 8080

spring:
  redis:
    port: 16379

  datasource:
    url: jdbc:h2:mem:event;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: event
    password:

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true

jwt:
  token-type: Bearer
  access-secret: 1234567890123456789012345678901234567890123456789012345678901234
  access-ttl: 24


logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    web: debug